### ISSUE TITLE
Плохая подписка на событие

### ISSUE THREAD

**Issue by zaverden** [MihailSverkunov/ikit-mita-hw3#2]
`numbertron.NewNumber += new Numbertron.NewNumberDelegate(jay.FetchNewNuber)`

 преобразование в делегат будет производиться автоматически, явно преобразование только отвлекает от сути. Надо:
`numbertron.NewNumber += jay.FetchNewNuber`

**Comment by MihailSverkunov** [comment]
Смотрел подписку на события у павловской в учебнике, у неё первый пример через new, а потом ниже нормальный идёт. Не заметил нижний, спасибо.
