### ISSUE TITLE
Очень странное дело

### ISSUE THREAD

**Issue by zaverden** [MihailSverkunov/ikit-mita-hw3#3]
зайди на https://github.com/MihailSverkunov/ikit-mita-hw3/commits/master и посмотри на автора "твоих" комитов

Выглядит крайне подозрительно. Особенно с учетом того, что для Анны я завожу те же самые замечания

**Comment by MihailSverkunov** [comment]
Здравствуйте, комит был мой. Лабу делал на её ноуте не дома, из акаунта не выходил(взял её ноут, потому что он заряд держит дольше чем мой). Подписку на события смотрели у павловской в учебнике, там сначала идёт пример с new, мы сделали как там не пролистав дальше, где была нормальная подписка. Всё сам писал, но проблему с выводом одного и того же числа в рандоме посмотрел у неё, в итоге не совсем верно.
